Upgraded nuget-packages within minor versions
ProCoSys/Bifrost pull request #70
Opened 2016-10-26 09:44 UTC by ThomasSL

2016-10-26 10:57 UTC, bnordli requested changes

2016-10-26 10:57 UTC, bnordli commented on Source/Bifrost.Client.Specs/Bifrost.Client.Specs.csproj
> +    <Reference Include="Machine.Specifications, Version=0.11.0.0, Culture=neutral, processorArchitecture=MSIL">
Look in .Source\Solutions\.nuget\packlages.config. There you'll find a solution wide reference that also should be updated.

2016-10-26 10:57 UTC, bnordli commented on Source/Bifrost.Default/Bifrost.Default.csproj
> +    <Reference Include="Microsoft.AspNet.SignalR.Core, Version=2.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
The old version number is still present in various Web.config and app.config files.

2016-10-26 10:57 UTC, bnordli commented on Source/Bifrost.NHibernate/Bifrost.NHibernate.csproj
> +    <Reference Include="FluentNHibernate, Version=2.0.3.0, Culture=neutral, processorArchitecture=MSIL">
You should update the version number in Bifrost.NHibernate.nuspec as well.

2016-10-26 10:57 UTC, bnordli commented on Source/Bifrost.NHibernate/Bifrost.NHibernate.csproj
> +      <HintPath>..\Solutions\packages\NHibernate.4.0.4.4000\lib\net40\NHibernate.dll</HintPath>
You should update the version number in Bifrost.NHibernate.nuspec as well.

2016-10-26 10:57 UTC, bnordli commented on Source/Bifrost.QuickStart/Bifrost.QuickStart.csproj
> +    <Content Include="Scripts\jquery.signalR-2.2.1.js" />
Keep these as embedded resources.

2016-10-26 10:57 UTC, bnordli commented on Source/Bifrost.Web/Bifrost.Web.csproj
> +    <NuGetPackageImportStamp>
Delete this.

2016-10-26 10:57 UTC, bnordli commented on Source/Bifrost.Web/Bifrost.Web.csproj
> +      <HintPath>..\Solutions\packages\WebActivatorEx.2.2.0\lib\net40\WebActivatorEx.dll</HintPath>
Update version number in Bifrost.Web.nuspec.

2016-10-26 10:57 UTC, bnordli commented on Source/Bifrost.Web/Bifrost.Web.csproj
> +    <Content Include="Scripts\jquery.signalR-2.2.1.js" />
Keep these as an embedded resource. You must also update the file name in ApplicationHttpHandler.

2016-10-26 10:57 UTC, bnordli commented on Source/Bifrost.Web/packages.config
> +  <package id="LessMsbuildTasks" version="1.0.10" targetFramework="net451" />
Update Bifrost.Web.nuspec with all the new packages versions from this file. (Or remove the lines from the nuspec file and verify that the dependencies in the NuGet package stays the same, it should be picked up automatically..)

2016-10-26 12:13 UTC, ThomasSL commented on Source/Bifrost.Client.Specs/Bifrost.Client.Specs.csproj
> +    <Reference Include="Machine.Specifications, Version=0.11.0.0, Culture=neutral, processorArchitecture=MSIL">
Runner is updated but do not have same version number as the other packages for Machine.Specifications.

2016-10-27 06:44 UTC, bnordli commented
You are still missing ApplicationHttpHandler.cs, it references the old signalR file.

2016-10-27 10:22 UTC, bnordli approved these changes

2016-10-27 10:22 UTC, merged